name: GitHub Actions Demo

on: 
  push: 
    branches: [main]
    paths-ignore: [./github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
      - run: | 
          echo "Hello hello "
          
      - uses: githubactions/checkout@v3.3.0

      - name: List files in repo
        run: | 
          echo " Hello again"
          tree
    

  
  
    
    
